////////////////////////////////////////////////
//// LOCAL TESTING 

// GET ALL CONTACTS
GET http://localhost:3000/users

// GET ONE CONTACT
### 
GET http://localhost:3000/users/62871ecd851bacd28d7c2bbb

// CREATE CONTACT
###
POST http://localhost:3000/users HTTP/1.1
content-type:application/json

{
    "username": "adsf",
    "displayName": "asdf",
    "email": "adsf@example.com",
    "password": "green",
    "phoneNumber": "155-555-5555"
}

// DELETE CONTACT
###
DELETE http://localhost:3000/users/628825a51ae3bbf1f0a86c22

// PUT UPDATE CONTACT
###
PUT http://localhost:3000/users/628825a51ae3bbf1f0a86c22 HTTP/1.1
Content-Type: application/json

{
    "password":"yellow"
}

/////////////////////////////////////////////////
//// HEROKU PUBLISHED

// GET ALL CONTACTS
###
GET https://cse341-project2-fullstackapp.herokuapp.com/users

// GET ONE CONTACT
### 
GET https://cse341-project2-fullstackapp.herokuapp.com/users/628826f9657006a71090727d

// CREATE CONTACT
###
POST https://cse341-project2-fullstackapp.herokuapp.com/users HTTP/1.1
content-type:application/json

{
    "username": "asdf",
    "displayName": "asdf",
    "email": "zach@example.com",
    "password": "red",
    "phoneNumber": "155-555-5555"
}

// DELETE CONTACT
###
DELETE https://cse341-project2-fullstackapp.herokuapp.com/users/628826f9657006a71090727d

// PUT UPDATE CONTACT
###
PUT https://cse341-project2-fullstackapp.herokuapp.com/users/628826f9657006a71090727d HTTP/1.1
Content-Type: application/json

{
    "password":"yellow"
}
