////////////////////////////////////////////////
//// LOCAL TESTING 

// GET ALL CONTACTS
GET http://localhost:8080/users

// GET ONE CONTACT
### 
GET http://localhost:8080/users/62871ee7851bacd28d7c2bbd

// CREATE CONTACT
###
POST http://localhost:8080/users HTTP/1.1
content-type:application/json

{
    "username":"Jim",
    "displayName":"Jimmy",
    "email":"Jim@example.com",
    "password": "password",
    "phoneNumber":"222-222-2222"
}

// DELETE CONTACT
###
DELETE http://localhost:8080/users/62871f25851bacd28d7c2bc2

// PUT UPDATE CONTACT
###
PUT http://localhost:8080/users/62871ee7851bacd28d7c2bbd HTTP/1.1
Content-Type: application/json

{
    "password":"yellow"
}

/////////////////////////////////////////////////
//// HEROKU PUBLISHED

// GET ALL CONTACTS
###
GET https://cse341-project2-fullstackapp.herokuapp.com/users

// GET ONE CONTACT
### 
GET https://cse341-project2-fullstackapp.herokuapp.com/users/62871ee7851bacd28d7c2bbd

// CREATE CONTACT
###
POST https://cse341-project2-fullstackapp.herokuapp.com/users HTTP/1.1
content-type:application/json

{
    "username":"Zach",
    "displayName":"Rochette",
    "email":"Zach@example.com",
    "password": "password",
    "phoneNumber":"222-222-2222"
}

// DELETE CONTACT
###
DELETE https://cse341-project2-fullstackapp.herokuapp.com/users/62871ee7851bacd28d7c2bbd

// PUT UPDATE CONTACT
###
PUT https://cse341-project2-fullstackapp.herokuapp.com/users/62871ecd851bacd28d7c2bbb HTTP/1.1
Content-Type: application/json

{
    "password":"yellow"
}
